// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "reminder.enabled": boolean;
      "mirror.extraField": boolean;
      "reminder.autoDays": number;
      "reminder.remindedMap": string;
      "collection.lastTarget": string;
    };
  }
}
